version: '3.3'

services:
  db:
    image: mysql:5.7
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql

volumes:
  db: 