env:
  node: true
  es2021: true
  mocha: true
extends:
  - trybe-backend
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - '@typescript-eslint'
rules:
  class-methods-use-this: 0
  "@typescript-eslint/no-unused-vars": "error"
settings:
  import/resolver: 
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx"]