"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Person_1 = require("./Person");
var Student_1 = require("./Student");
var Subject_1 = require("./Subject");
var Teacher_1 = require("./Teacher");
var jeff = new Person_1.default('Jeff', new Date('2000/08/07'));
var robertin = new Person_1.default('Robertin', new Date('1980/01/01'));
console.log(jeff);
console.log(robertin);
var student01 = new Student_1.default(jeff);
var student02 = new Student_1.default(robertin);
console.log(student01);
console.log(student02);
var math = new Subject_1.default('Math');
var history = new Subject_1.default('History');
var philosophy = new Subject_1.default('Filosofia');
var marcos = new Person_1.default('Marcos', new Date('1981/01/01'));
var mathTeacher = new Teacher_1.default(marcos.name, marcos.birthDate, math, 1600, new Date('2020/03/01'));
var joao = new Person_1.default('Joao', new Date('1990/03/01'));
var historyTeacher = new Teacher_1.default(joao.name, joao.birthDate, history, 1500, new Date('2021/04/01'));
var marcelo = new Person_1.default('Marcelo', new Date('1983/07/01'));
var philosophyTeacher = new Teacher_1.default(marcelo.name, marcelo.birthDate, philosophy, 1500, new Date('2021/02/01'));
console.log(mathTeacher);
console.log(historyTeacher);
console.log(philosophyTeacher);
