version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: db-mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - backend

networks:
  backend:

volumes:
  db: