"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const EvaluationResult_1 = require("./EvaluationResult");
const Exam_1 = require("./Exam");
const Student_1 = require("./Student");
const Subject_1 = require("./Subject");
const Teacher_1 = require("./Teacher");
const Work_1 = require("./Work");
const student01 = new Student_1.Student('Jeff', new Date('2000/08/07'));
const student02 = new Student_1.Student('Robertin', new Date('1980/01/01'));
console.log(student01);
console.log(student02);
const math = new Subject_1.Subject('Math');
const history = new Subject_1.Subject('History');
const philosophy = new Subject_1.Subject('Filosofia');
const Marcos = new Teacher_1.Teacher('Marcos', new Date('1981/01/01'), 1600, math);
const Joao = new Teacher_1.Teacher('Joao', new Date('1990/03/01'), 1500, history);
const Marcelo = new Teacher_1.Teacher('Marcelo', new Date('1983/07/01'), 1500, philosophy);
const mathExam = new Exam_1.Exam(25, Marcos);
const mathWork = new Work_1.Work(50, Marcos);
const historyExam = new Exam_1.Exam(25, Joao);
const historyWork = new Work_1.Work(50, Joao);
console.log(Marcos);
console.log(Joao);
console.log(Marcelo);
student01.addEvaluationResult(new EvaluationResult_1.EvaluationResult(mathExam, 15));
student01.addEvaluationResult(new EvaluationResult_1.EvaluationResult(mathWork, 40));
student01.addEvaluationResult(new EvaluationResult_1.EvaluationResult(historyExam, 15));
student01.addEvaluationResult(new EvaluationResult_1.EvaluationResult(historyWork, 40));
console.log('Avaliações: ', student01.evaluationsResults);
console.log('Soma das notas: ', student01.sumGrades());
console.log('Média das notas: ', student01.sumAverageGrades());
